In [1]:
import tensorflow as tf
import numpy as np

In [15]:
xy = np.loadtxt('train_logistic', unpack=True, dtype='float32')

(3, 6)


array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  3.,  5.,  7.,  2.],
       [ 1.,  2.,  4.,  5.,  5.,  5.]], dtype=float32)

In [20]:
xy

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  3.,  5.,  7.,  2.],
       [ 1.,  2.,  4.,  5.,  5.,  5.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]], dtype=float32)

In [21]:
x_data = xy[0:-1]
print(x_data.shape)
x_data

(3, 6)


array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  3.,  5.,  7.,  2.],
       [ 1.,  2.,  4.,  5.,  5.,  5.]], dtype=float32)

In [16]:
y_data = xy[-1]
print(y_data.shape)
y_data

(6,)


array([ 0.,  0.,  0.,  1.,  1.,  1.], dtype=float32)

In [5]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [19]:
W = tf.Variable(tf.random_uniform([1, len(x_data)], -1.0, 1.0))
W

In [7]:
h = tf.matmul(W, X)
hypo = tf.sigmoid(h)

In [8]:
cost = -tf.reduce_mean(Y*tf.log(hypo) + (1-Y)*tf.log(1-hypo))

In [10]:
alpha = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(alpha)
train = optimizer.minimize(cost)

In [11]:
init = tf.initialize_all_variables()

In [12]:
sess = tf.Session()

In [13]:
sess.run(init)
for step in range(2000):
    sess.run(train, feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print("step : ", step)
        print("cost : ", sess.run(cost, feed_dict={X:x_data, Y:y_data}))
        print("W : ", sess.run(W))
        print("="*50)

step :  0
cost :  0.937209
W :  [[-0.5166055   0.1986748   0.68511277]]
step :  200
cost :  0.375546
W :  [[ -2.37892962e+00  -1.84560567e-03   7.29538143e-01]]
step :  400
cost :  0.307608
W :  [[-3.52077723  0.08173866  0.91581196]]
step :  600
cost :  0.27058
W :  [[-4.36500502  0.13042119  1.06450677]]
step :  800
cost :  0.246514
W :  [[-5.04568386  0.16169848  1.19060075]]
step :  1000
cost :  0.229103
W :  [[-5.62445116  0.18314782  1.30163741]]
step :  1200
cost :  0.215591
W :  [[-6.13407469  0.19850229  1.40196133]]
step :  1400
cost :  0.204584
W :  [[-6.59385204  0.20982464  1.49427223]]
step :  1600
cost :  0.195296
W :  [[-7.0160079   0.21835342  1.58034754]]
step :  1800
cost :  0.187252
W :  [[-7.40872526  0.22487746  1.66141307]]
