# TensorFlow Basic Exercise #1
* Step1 : Define Constant
* Step2 : Define Variable
* Step3 : Make Matrix
* Step4 : Matrix Production
* Step5 : Make Mean

### tensorflow 를 import 할 수 있어야 합니다

In [1]:
import tensorflow as tf

## Step1. Define Constant : 상수 정의

In [2]:
a = tf.constant([1,2,3])
b = tf.constant([[10, 20, 30], [100, 200, 300]])
c = tf.add(a, b)

### Tensor 를 만들고 실행시키고 싶다면 :

In [3]:
with tf.Session() as sess:
    print(sess.run(c))

[[ 11  22  33]
 [101 202 303]]


### 만약 여기서 그냥 print(c) 를 한다면?

In [4]:
print(c)

Tensor("Add:0", shape=(2, 3), dtype=int32)



## Step2. Tensor Concept : 텐서의 개념잡기
### Define Variable : 변수 정의

In [6]:
var = tf.Variable(0, name="counter")

In [7]:
init = tf.initialize_all_variables()

In [8]:
sess = tf.Session()
sess.run(init)
print(sess.run(var))

0


### 그럼 여기서 var 변수의 값을 2로 바꾸겠습니다.

In [9]:
var.assign(2)
print(sess.run(var))

0


### 오잉? 왜 2가 안되고 그대로 0이죠?
* 여기서 변수값이 2이 아니라 그전 변수값인 0이 나온 이유는 
* state1.assign(2) 자체는 tensor 를 생성하는 행위이고
* 따라서 변수값 변경이 적용되도록 만드려면, 다음과 같이 작업해주어야 합니다.

In [9]:
assign_op = var.assign(2)

In [10]:
sess.run(assign_op)

2

In [11]:
sess.run(var)

2

### Step2 에서는 왜 tf.Session() 을 run 해야 하는지를 이해하시면 됩니다 :)

## Step3. Make Matrix : 행렬 만들기

In [12]:
zeros = tf.zeros([3,]) # 이렇게 쓰면 벡터를 만듭니다.
sess.run(zeros)

array([ 0.,  0.,  0.], dtype=float32)

### 랜덤한 매트릭스를 만드는 방법은?
* random_uniform : 균등분포에서 아무값을 뽑아내는 행위 : 랜덤값을 얻는 방법

In [13]:
mat1 = tf.random_uniform([1], -1, 1) # 인자값 : 매트릭스 크기, 시작 범위값, 끝 범위값

In [14]:
mat2 = tf.random_uniform([2,2], -1, 1)

In [15]:
sess.run(mat1)

array([ 0.68649888], dtype=float32)

In [16]:
sess.run(mat2)

array([[-0.76678348, -0.94451833],
       [-0.39745784,  0.66651154]], dtype=float32)

### 매트릭스의 곱셈은?
* matmul(mat1, mat2) : 곱셈의 shape 는 맞아야 합니다

In [17]:
mat1 = tf.constant([[2, 3]])
mat2 = tf.constant([[3], [4]])

In [18]:
product = tf.matmul(mat1, mat2)

In [19]:
sess.run(mat1)

array([[2, 3]], dtype=int32)

In [20]:
sess.run(mat2)

array([[3],
       [4]], dtype=int32)

In [21]:
sess.run(product)

array([[18]], dtype=int32)

In [22]:
sess.run(product).shape # 얘도 매트릭스네요

(1, 1)

In [23]:
cons = tf.constant(1)
sess.run(cons).shape # 상수는 이렇게 표현되네요

()

## Step4. Tensorflow vs Python Product : 행렬의 곱셈

### python 의 기본 곱하기(*) ?

In [10]:
x = [1, 2, 3]

In [13]:
prod1 = 2*x
print("="*40)

### numpy 의 기본 곱셈 ?

In [15]:
import numpy as np

In [16]:
prod2 = 2*np.array(x)
prod2

array([2, 4, 6])

### tensorflow 의 기본 곱셈 ?

In [28]:
prod3 = tf.constant(2)*x
sess.run(prod3)

array([2, 4, 6], dtype=int32)

* tensorflow sess.run 결과의 type을 확인해보세요

## Step5. Mean : 평균 구하기

### numpy 에서의 평균
* numpy.mean(array, slice) : slice(none) : total, slice(0) : columnwise, slice(1) : rowwise

In [29]:
np_array = np.array([[1,2], [3,4], [5,6]])
np_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
print("rowwise mean : ", np.mean(np_array, 1))
print("columnwise mean : ", np.mean(np_array, 0))
print("total mean : ", np.mean(np_array))

rowwise mean :  [ 1.5  3.5  5.5]
columnwise mean :  [ 3.  4.]
total mean :  3.5


### tensorflow 에서의 평균
* reduce_mean : np.mean 과 동일하게 작동한다.

In [33]:
mean_row = tf.reduce_mean(np_array, 1)
mean_col = tf.reduce_mean(np_array, 0)
mean_total = tf.reduce_mean(np_array)

In [36]:
print("rowwise mean : ", sess.run(mean_row))
print("columnwise mean : ", sess.run(mean_col))
print("total mean : ", sess.run(mean_total))

rowwise mean :  [1 3 5]
columnwise mean :  [3 4]
total mean :  3


### 여기서 한가지, array 가 int 형을 경우에는 tensorflow 는 정수 연산만 수행한다. 그럼 정확한 값을 원할때는 ?

In [40]:
c = np.array([[1., 2], [3, 4], [5 ,6]])

In [41]:
mean_row = tf.reduce_mean(c, 1)
mean_col = tf.reduce_mean(c, 0)
mean_total = tf.reduce_mean(c)

In [42]:
print("rowwise mean : ", sess.run(mean_row))
print("columnwise mean : ", sess.run(mean_col))
print("total mean : ", sess.run(mean_total))

rowwise mean :  [ 1.5  3.5  5.5]
columnwise mean :  [ 3.  4.]
total mean :  3.5


### 만약 numpy.array 를 쓰지 않고, 그냥 리스트를 넣는다면 가능할까?

In [43]:
c = [[1., 2], [3,4], [5,6]]
c

[[1.0, 2], [3, 4], [5, 6]]

In [44]:
mean_row = tf.reduce_mean(c, 1)
mean_col = tf.reduce_mean(c, 0)
mean_total = tf.reduce_mean(c)

In [45]:
print("rowwise mean : ", sess.run(mean_row))
print("columnwise mean : ", sess.run(mean_col))
print("total mean : ", sess.run(mean_total))

rowwise mean :  [ 1.5  3.5  5.5]
columnwise mean :  [ 3.  4.]
total mean :  3.5


### 결론 : 가능합니다 :) 평균을 행렬의 가로방향 또는 세로방향 또는 전체 등 어떤 방향으로 구할지를 명확하게 이해해야 합니다.