# "Deep" Neural Network with XOR problem

## using TensorBoard

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('train_nn_xor.txt', unpack=False)
x_data = xy[:, 0:-1]
y_data = np.reshape(xy[:, -1], (4,1))
print(x_data)
print(y_data)

[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]


In [3]:
X = tf.placeholder(tf.float32, name="X-input")
Y = tf.placeholder(tf.float32, name="Y-input")

In [4]:
# Deep network configuration.: Use more layers. 
W1 = tf.Variable(tf.random_uniform( [2,5], -1.0, 1.0),name = 'weight1')
W2 = tf.Variable(tf.random_uniform( [5,4], -1.0, 1.0),name = 'weight2')
W3 = tf.Variable(tf.random_uniform( [4,1], -1.0, 1.0),name = 'weight3')

In [5]:
b1 = tf.Variable(tf.zeros([5]), name="bias1")
b2 = tf.Variable(tf.zeros([4]), name="bias2")
b3 = tf.Variable(tf.zeros([1]), name="bias3")

In [6]:
# Define Histogram Summary
w1_histo = tf.histogram_summary("weight1", W1)
w2_histo = tf.histogram_summary("weight2", W2)
w3_histo = tf.histogram_summary("weight3", W3)

In [7]:
# Define Scalar Summary
b1_histo = tf.histogram_summary("biases1", b1)
b2_histo = tf.histogram_summary("biases2", b2)
b3_histo = tf.histogram_summary("biases3", b3)

In [8]:
y_histo = tf.histogram_summary("place_y", Y)

In [9]:
# Define Scope with Hypothesis
with tf.name_scope("layer2") as scope:
    L2 = tf.sigmoid(tf.matmul(X, W1) + b1)

with tf.name_scope("layer3") as scope:
    L3 = tf.sigmoid(tf.matmul(L2, W2) + b2)

with tf.name_scope("layer4") as scope:
    hypo = tf.sigmoid(tf.matmul(L3, W3) + b3)

In [10]:
# Define Cost Function with scope
with tf.name_scope("cost_function") as scope:
    cost = -tf.reduce_mean(Y*tf.log(hypo) + (1-Y)*tf.log(1. - hypo))
    cost_scar = tf.scalar_summary("cost", cost)


In [11]:
# Define Train Logic with scope
alpha = tf.Variable(0.1)
with tf.name_scope("train") as scope:
    optimizer = tf.train.GradientDescentOptimizer(alpha)
    train = optimizer.minimize(cost)


In [12]:
init = tf.initialize_all_variables()
with tf.Session() as sess:
    # Marge Summaries
    merged = tf.merge_all_summaries()
    writer = tf.train.SummaryWriter('./tensorboard/DeepNN2', sess.graph)
    
    # init variables
    sess.run(init)
    
    for step in range(10001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            print("step : ", step)
            print("cost : ", sess.run(cost, feed_dict={X:x_data, Y:y_data}))
            print("W1 : \n", sess.run(W1))
            print("W2 : \n", sess.run(W2))
            print("W3 : \n", sess.run(W3))
            print("="*60)
            
            summary = sess.run(merged, feed_dict={X:x_data, Y:y_data})
            writer.add_summary(summary, step)
        
    
    # Test Model
    correct_prediction = tf.equal(tf.floor(hypo + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, 'float'))
    
    # Check Accuracy
    print("hypo : \n", sess.run(hypo, feed_dict={X:x_data, Y:y_data}))
    print("floor : \n", sess.run(tf.floor(hypo+0.5), feed_dict={X:x_data, Y:y_data}))
    print("correct_prediction : \n", sess.run(correct_prediction, feed_dict={X:x_data, Y:y_data}))
    print("accuracy : \n", sess.run(accuracy, feed_dict={X:x_data, Y:y_data}))
    

step :  0
cost :  0.76108
W1 : 
 [[ 0.01974434 -0.99958456  0.02618453  0.85854793 -0.07320779]
 [-0.92627096  0.3410019   0.59965938 -0.6505     -0.82240695]]
W2 : 
 [[ 0.04008046 -0.82403541 -0.66884452  0.05348672]
 [ 0.66839582 -0.70012367  0.38191846 -0.50685328]
 [-0.3316125  -0.86369973  0.41306058 -0.48190263]
 [-0.50960767 -0.85956419 -0.40235081  0.88436371]
 [-0.09054393 -0.25807095 -0.26899168  0.4191457 ]]
W3 : 
 [[ 0.0680053 ]
 [-0.9725486 ]
 [-0.89077693]
 [-0.43748528]]
step :  2000
cost :  0.692301
W1 : 
 [[ 0.1356919  -1.15567648 -0.00182854  0.75413841 -0.05813748]
 [-0.93517154  0.43642408  0.59414715 -0.68951225 -0.81310099]]
W2 : 
 [[ 0.0270965  -0.83572924 -0.64208782  0.0863625 ]
 [ 0.70616478 -0.84274101  0.27125862 -0.53248334]
 [-0.32236186 -0.88244617  0.39513165 -0.46248803]
 [-0.52767515 -0.80637413 -0.34016913  0.93285567]
 [-0.11310515 -0.26283908 -0.22649026  0.45976824]]
W3 : 
 [[ 0.36118576]
 [-0.9482953 ]
 [-0.59997243]
 [-0.35442325]]
step :  4000
c

## Launch tensorboard 
* tensorboard --logdir=your tensorboard file