# TensorFlow Basic Exercise #1
* Step1 : Define Constant
* Step2 : Define Variable
* Step3 : Make Matrix
* Step4 : Matrix Production

### tensorflow 를 import 할 수 있어야 합니다

In [5]:
import tensorflow as tf

## Step1. Define Constant : 상수 정의

In [2]:
a = tf.constant([1,2,3])
b = tf.constant([[10, 20, 30], [100, 200, 300]])
c = tf.add(a, b)

### Tensor 를 만들고 실행시키고 싶다면 :

In [3]:
with tf.Session() as sess:
    print(sess.run(c))

[[ 11  22  33]
 [101 202 303]]


### 만약 여기서 그냥 print(c) 를 한다면?

In [4]:
print(c)

Tensor("Add:0", shape=(2, 3), dtype=int32)



## Step2. Tensor Concept : 텐서의 개념잡기
### Define Variable : 변수 정의

In [6]:
var = tf.Variable(0, name="counter")

In [7]:
init = tf.initialize_all_variables()

In [11]:
sess = tf.Session()
sess.run(init)
print(sess.run(var))

0


### 그럼 여기서 var 변수의 값을 2로 바꾸겠습니다.

In [12]:
var.assign(2)
print(sess.run(var))

0


### 오잉? 왜 2가 안되고 그대로 0이죠?
* 여기서 변수값이 2이 아니라 그전 변수값인 0이 나온 이유는 
* state1.assign(2) 자체는 tensor 를 생성하는 행위이고
* 따라서 변수값 변경이 적용되도록 만드려면, 다음과 같이 작업해주어야 합니다.

In [13]:
assign_op = var.assign(2)

In [14]:
sess.run(assign_op)

2

In [15]:
sess.run(var)

2

### Step2 에서는 왜 tf.Session() 을 run 해야 하는지를 이해하시면 됩니다 :)

## Step3. Make Matrix : 행렬 만들기

In [17]:
zeros = tf.zeros([3,]) # 이렇게 쓰면 벡터를 만듭니다.
sess.run(zeros)

array([ 0.,  0.,  0.], dtype=float32)

### 랜덤한 매트릭스를 만드는 방법은?
* random_uniform : 균등분포에서 아무값을 뽑아내는 행위 : 랜덤값을 얻는 방법

In [18]:
mat1 = tf.random_uniform([1], -1, 1) # 인자값 : 매트릭스 크기, 시작 범위값, 끝 범위값

In [19]:
mat2 = tf.random_uniform([2,2], -1, 1)

In [20]:
sess.run(mat1)

array([ 0.80197978], dtype=float32)

In [21]:
sess.run(mat2)

array([[ 0.67395902,  0.98391485],
       [ 0.52746654,  0.43340039]], dtype=float32)

### 매트릭스의 곱셈은?
* matmul(mat1, mat2) : 곱셈의 shape 는 맞아야 합니다

In [22]:
mat1 = tf.constant([[2, 3]])
mat2 = tf.constant([[3], [4]])

In [23]:
product = tf.matmul(mat1, mat2)

In [25]:
sess.run(mat1)

array([[2, 3]], dtype=int32)

In [26]:
sess.run(mat2)

array([[3],
       [4]], dtype=int32)

In [27]:
sess.run(product)

array([[18]], dtype=int32)

In [28]:
sess.run(product).shape # 얘도 매트릭스네요

(1, 1)

In [29]:
cons = tf.constant(1)
sess.run(cons).shape # 상수는 이렇게 표현되네요

()

## Step4. Tensorflow vs Python Product : 행렬의 곱셈

### python 의 기본 곱하기(*) ?

In [30]:
x = [1, 2, 3]

In [43]:
prod1 = 2*x

### numpy 의 기본 곱셈 ?

In [32]:
import numpy as np

In [41]:
prod2 = 2*np.array(x)

### tensorflow 의 기본 곱셈 ?

In [40]:
prod3 = tf.constant(2)*x
sess.run(prod3)

array([2, 4, 6], dtype=int32)

* tensorflow sess.run 결과의 type을 확인해보세요