# Tensorflow Softmax Tutorial

In [1]:
import tensorflow as tf
import numpy as np

## 데이터를 로드할 때, 어떠한 구조로 가져올 것인지 결정하는 것이 중요합니다

### 만약 파일에서, 하나의 row 가 하나의 데이터를 의미하고, column 이 attribute 를 의미한다면
* unpack = True 로 가져오면, row 가 attributes 를 표현하게 됩니다. (Transpose 한 효과)
* unpack = False 로 가져오면, row 가 그대로 하나의 데이터 정보로 유지가 됩니다.

In [3]:
xy = np.loadtxt('train_softmax.txt', unpack=True, dtype='float32')
xy

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  3.,  5.,  7.,  2.,  6.,  7.],
       [ 1.,  2.,  4.,  5.,  5.,  5.,  6.,  7.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [26]:
xy2 = np.loadtxt('train_softmax.txt', unpack=False, dtype='float32')
xy2

array([[ 1.,  2.,  1.,  0.,  0.,  1.],
       [ 1.,  3.,  2.,  0.,  0.,  1.],
       [ 1.,  3.,  4.,  0.,  0.,  1.],
       [ 1.,  5.,  5.,  0.,  1.,  0.],
       [ 1.,  7.,  5.,  0.,  1.,  0.],
       [ 1.,  2.,  5.,  0.,  1.,  0.],
       [ 1.,  6.,  6.,  1.,  0.,  0.],
       [ 1.,  7.,  7.,  1.,  0.,  0.]], dtype=float32)

### row 기준의 데이터의 형태를 유지시켜 주는 것이, 행렬 계산할 때, 비교적 헷갈리지 않습니다.

### 대신 그러기 위해서는 매트릭스 곱셈을 수행할 때는 
### 우리가 일반적으로 생각하는 W*X 형태가 아닌,
### X*W 형태가 됩니다.  (결과만 동일하면 되기 때문에, 크게 문제가 되지는 않습니다.)

In [4]:
# unpack = True 라면 아래와 같이 데이터를 뽑아내고,
x_data = np.transpose(xy[0:3])
x_data

array([[ 1.,  2.,  1.],
       [ 1.,  3.,  2.],
       [ 1.,  3.,  4.],
       [ 1.,  5.,  5.],
       [ 1.,  7.,  5.],
       [ 1.,  2.,  5.],
       [ 1.,  6.,  6.],
       [ 1.,  7.,  7.]], dtype=float32)

In [30]:
# unpack = False 라면 아래와 같이 데이터를 뽑아냅니다.
x_data2 = xy2[:,0:3]
x_data2

array([[ 1.,  2.,  1.],
       [ 1.,  3.,  2.],
       [ 1.,  3.,  4.],
       [ 1.,  5.,  5.],
       [ 1.,  7.,  5.],
       [ 1.,  2.,  5.],
       [ 1.,  6.,  6.],
       [ 1.,  7.,  7.]], dtype=float32)

In [5]:
y_data = np.transpose(xy[3:])
y_data

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]], dtype=float32)

In [7]:
X = tf.placeholder('float', [None, 3]) # (?, 3) 형태의 매트릭스가 들어올 공간을 정의합니다. 여기서는 x0, x1, x2 가 들어오겠군요.
Y = tf.placeholder('float', [None, 3]) # 마찬가지

In [8]:
W = tf.Variable(tf.zeros([3,3]))

In [9]:
hypo = tf.nn.softmax(tf.matmul(X, W))

In [10]:
alpha = 0.001
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypo), reduction_indices=1))

In [11]:
optimizer = tf.train.GradientDescentOptimizer(alpha).minimize(cost)

In [12]:
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

In [15]:
for step in range(2000):
    sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print("step : ", step)
        print("cost : ", sess.run(cost, feed_dict={X:x_data, Y:y_data}))
        print(sess.run(W))
        print("="*60)
        

step :  0
cost :  1.09608
[[-0.00025136  0.00012188  0.00012948]
 [ 0.00049295  0.00085905 -0.00135199]
 [ 0.00049303  0.0012341  -0.00172713]]
step :  200
cost :  1.05951
[[-0.02073397 -0.00108681  0.02182078]
 [ 0.01411936  0.0109053  -0.02502465]
 [ 0.01437138  0.03591624 -0.0502876 ]]
step :  400
cost :  1.04976
[[-0.04305011 -0.00631357  0.04936369]
 [ 0.01749462  0.00146169 -0.0189563 ]
 [ 0.01834226  0.04966335 -0.06800557]]
step :  600
cost :  1.04061
[[-0.06540124 -0.01181888  0.07722014]
 [ 0.01945293 -0.00858766 -0.01086525]
 [ 0.02118363  0.06129476 -0.0824783 ]]
step :  800
cost :  1.03186
[[-0.08756066 -0.0173492   0.1049099 ]
 [ 0.02113326 -0.01805311 -0.00308015]
 [ 0.02399478  0.07208792 -0.09608269]]
step :  1000
cost :  1.02346
[[-0.1095041  -0.02287706  0.13238117]
 [ 0.02267741 -0.02686532  0.00418794]
 [ 0.02688788  0.08220155 -0.10908943]]
step :  1200
cost :  1.01539
[[-0.13123088 -0.02839605  0.15962695]
 [ 0.02411086 -0.03505516  0.01094435]
 [ 0.02986211  0.0

### 여기서 우리가 row 형태의 데이터 형식을 유지시켜준 편의를 느낄 수 있습니다

In [20]:
data_a = [1,11,7]
a = sess.run(hypo, feed_dict={X:[data_a]})
print(a, sess.run(tf.arg_max(a, 1)))

[[ 0.46275628  0.35479435  0.18244931]] [0]


In [21]:
data_c = [1,1,0]
c = sess.run(hypo, feed_dict={X:[data_c]})
print(c, sess.run(tf.arg_max(c, 1)))

[[ 0.26998979  0.29083177  0.4391785 ]] [2]


In [23]:
data_b = [1, 3, 4]
b = sess.run(hypo, feed_dict={X:[data_b]})
print(b,sess.run(tf.arg_max(b, 1)))

[[ 0.33819196  0.42102447  0.24078354]] [1]


In [25]:
alls = sess.run(hypo, feed_dict={X:[data_a, data_b, data_c]})
print(alls)
print(sess.run(tf.arg_max(alls, 1)))

[[ 0.46275634  0.35479441  0.18244931]
 [ 0.33819196  0.42102447  0.24078354]
 [ 0.26998979  0.29083174  0.4391785 ]]
[0 1 2]
